import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

live_config_reload = true

[shell]
program = "tmux"

[window]
startup_mode = "Windowed"
decorations = "Transparent"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[scrolling]
history = 10000

[font]
normal = { family = "Monospace", style = "Regular" }
bold = { family = "Monospace", style = "Bold" }
italic = { family = "Monospace", style = "Italic" }
bold_italic = { family = "Monospace", style = "Bold Italic" }
size = 12.0

[cursor]
style = "Underline"

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
    { mouse = "Middle", action = "Paste" },
]

[debug]
render_timer = false
print_events = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "L", mods = "Control|Shift", action = "ClearHistory" },
    { key = "PageUp", mods = "Control", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control", action = "ScrollPageDown" },
    { key = "Home", mods = "Control", action = "ScrollToTop" },
    { key = "End", mods = "Control", action = "ScrollToBottom" },
    { key = "Backspace", mods = "Control", chars = "\u001b\u007f" }
]